@host = https://localhost:7202

### Get sea conditions (failure rate controlled by FAILURE_RATE env var)
GET {{host}}/conditions
Accept: application/json

### Get OpenAPI document
GET {{host}}/openapi/v1.json
Accept: application/json
